kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-one
  namespace: vigneshbaskar-dev
  uid: f8677d59-14c4-4bfd-97c9-86130eaa20a3
  resourceVersion: '4271329146'
  generation: 16
  creationTimestamp: '2025-10-23T11:20:10Z'
  annotations:
    deployment.kubernetes.io/revision: '7'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4"},"name":"deploy-one","namespace":"vigneshbaskar-dev"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"deploy-one"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-10-23T19:09:54+05:30","prometheus.io/port":"9100","prometheus.io/scrape":"true"},"labels":{"app":"deploy-one"}},"spec":{"containers":[{"image":"prom/node-exporter:latest","imagePullPolicy":"Always","name":"container","ports":[{"containerPort":9100,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-23T11:20:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"container"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kubectl-replace
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-23T14:24:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                'f:prometheus.io/port': {}
                'f:prometheus.io/scrape': {}
            'f:spec':
              'f:containers':
                'k:{"name":"container"}':
                  'f:image': {}
                  'f:ports':
                    'k:{"containerPort":9100,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-23T15:49:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
    - manager: kubectl-rollout
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-23T15:49:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:kubectl.kubernetes.io/restartedAt': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-11-04T10:03:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-one
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-one
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-10-23T21:19:26+05:30'
        prometheus.io/port: '9100'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: container
          image: 'prom/node-exporter:latest'
          ports:
            - containerPort: 9100
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 16
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-10-23T15:49:29Z'
      lastTransitionTime: '2025-10-23T11:20:10Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "deploy-one-5ff9fcb8f6" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-11-04T10:03:26Z'
      lastTransitionTime: '2025-11-04T10:03:26Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
