---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: vigneshbaskar-dev
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: pod-logs
        static_configs:
          - targets: [localhost]
            labels:
              job: pod-logs
              __path__: /var/log/pods/**/*.log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: vigneshbaskar-dev
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: default
      containers:
        - name: promtail
          image: grafana/promtail:3.1.1
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: positions
              mountPath: /tmp
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 64Mi

        # 🟢 Log generator container — writes dummy logs for Promtail to pick up
        - name: log-generator
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - >
              while true; do
                echo "$(date) - Hello Loki from Promtail POC!" >> /var/log/pods/sample.log;
                sleep 5;
              done
          volumeMounts:
            - name: varlog
              mountPath: /var/log

      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          emptyDir: {}
        - name: positions
          emptyDir: {}
