---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: vigneshbaskar-dev
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      # Read logs from the shared /var/log/app-logs directory
      - job_name: app-logs
        static_configs:
          - targets: [localhost]
            labels:
              job: app-logs
              __path__: /var/log/app-logs/*.log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: vigneshbaskar-dev
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: default
      containers:
        - name: promtail
          image: grafana/promtail:3.1.1
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: app-logs
              mountPath: /var/log/app-logs
            - name: positions
              mountPath: /tmp
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: app-logs
          emptyDir: {}   # shared directory where app logs will be written
        - name: positions
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: vigneshbaskar-dev
spec:
  selector:
    app: promtail
  ports:
    - name: http
      port: 9080
      targetPort: 9080
